# This is a basic workflow to help you get started with Actions

name: linter

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: reviewdog/action-cpplint@master
      with:
        github_token: ${{ secrets.REVIEW_ACCOUNT }}
        reporter: github-pr-review
        filter: "-readability/braces\
          ,-whitespace/braces\
          ,-whitespace/comments\
          ,-whitespace/indent\
          ,-whitespace/newline\
          ,-whitespace/operators\
          ,-whitespace/parens\
          ,-whitespace/tab\
          ,-runtime/references\
          " # Optional
